TestFolder1/BackgroundService:
  url: "/background"
  policy: "TestFolder1/BackgroundService"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
  wssProcessingEnabled: false
